name: face_detection_camera
description: "Smart Flutter camera with face detection, look-straight constraints, auto-capture, and customizable overlay."
version: 0.1.0
homepage: https://github.com/ngtrongha/face_detection_camera
repository: https://github.com/ngtrongha/face_detection_camera

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
